/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a067fbcd-0e1c-4356-a2b8-56f44a0e5818",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dCmFyjerf",
    "aws_user_pools_web_client_id": "1f0ce20166sat38slk8ptjvbjn",
    "oauth": {},
    "aws_mobile_analytics_app_id": "d0599af832fd48b2992ef9766fa8162e",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3mhgpcoasbaibmjtnzc2bg56j4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xd7mnaipxvbjhma5vcq2akhjka"
};


export default awsmobile;
